### ISSUE TITLE
Just wondering if anyone has a grafana dashboard using these exported metrics?

### ISSUE THREAD

**Issue by brokenjacobs** [sapcc/mosquitto-exporter#21]
If not, whenever I get one together I'll tack it onto this issue. It would be handy.

**Comment by mnezerka** [comment]
Yes, I use your exporter to feed my Prometheus which serves data to Grafana dashboard.
.

**Comment by tg44** [comment]
Would love one :D

**Comment by tg44** [comment]
I uploaded one: https://grafana.com/grafana/dashboards/11542

**Comment by ngosang** [comment]
@tg44 thank you. I just made minor improvements in your dashboard.

[mosquitto_dashboard.txt](https://github.com/sapcc/mosquitto-exporter/files/9272894/mosquitto_dashboard.txt)

![image](https://user-images.githubusercontent.com/10577978/183207996-30b0e523-5e86-42d2-9a84-657311e770c7.png)

**Comment by reefland** [comment]
@tg44 / @ngosang  - Added a bit more...

![image](https://user-images.githubusercontent.com/16230914/184017797-c62eeadd-d519-44cb-a81e-2d9993840c40.png)

[mosquitto_dashboard.txt](https://github.com/sapcc/mosquitto-exporter/files/9303964/mosquitto_dashboard.txt)

**Comment by brokenjacobs** [comment]
Awesome thank you for sharing! Closing this issue.

**Comment by Strykar** [comment]
> 
> [mosquitto_dashboard.txt](https://github.com/sapcc/mosquitto-exporter/files/9303964/mosquitto_dashboard.txt)

@reefland Thanks for this, but my dashboard does not show received data or correct client numbers, how do I troubleshoot this?
![image](https://user-images.githubusercontent.com/2946372/209045943-f4f1a69a-50a5-49b4-b965-4c16e83a12a8.png)

**Comment by reefland** [comment]
Within the Prometheus GUI, you can make queries of the data directly. Such as:

Total Clients:  `broker_clients_total` and click [Execute].  That should return the value scraped from mosquitto-exporter:

![image](https://user-images.githubusercontent.com/16230914/209051555-4daa935f-4c20-41b6-8a2e-3400e295d125.png)
* So I have  9 clients connected.

Same for `broker_messages_received`:
![image](https://user-images.githubusercontent.com/16230914/209051693-1ef0ea1c-b4ef-47be-8704-f1cbb1486f3d.png)
* 3.3 Million messages since last restart

You can also query the source directly using `curl`.   Figure out which node it is running on:

```
$ kubectl get pods -n mosquitto -owide | grep exporter
mosquitto-exporter-58cf56c8b5-gpjss   1/1     Running   0          6d7h   10.42.3.44   k3s04   <none>           <none>
```

For me that is node `k3s04`, and above provided the pod IP address `10.42.3.44`. So I SSH to that node and query directly:

```
$ curl -s http://10.42.3.44:9234/metrics | grep clients_total

# HELP broker_clients_total $SYS/broker/clients/total
# TYPE broker_clients_total counter
broker_clients_total 9
```

That shows you the path within the broker and the value.  

Lastly, you can login using a client like MQTT Explorer to see what the values are within the broker.

**Comment by Strykar** [comment]
@reefland Thank you for the pointers, but something is off.
The mosquitto_exporter does not see `clients_total` but logging in with the same credentials using `mqtt-explorer` shows the client count and messages received.
```
$ curl -s  http://127.0.0.1:9234/metrics | grep clients_total
$
$ curl -s  http://127.0.0.1:9234/metrics | grep broker_bytes_received
# HELP broker_bytes_received $SYS/broker/bytes/received
# TYPE broker_bytes_received counter
broker_bytes_received 17461
```
![image](https://user-images.githubusercontent.com/2946372/209160665-2d215f12-bf0f-437c-827e-17fce39cb577.png)

I've double checked the data source and it seems broker_subscription_count is not a metric from Prometheus on my instance:
![image](https://user-images.githubusercontent.com/2946372/209161750-fcbb8b9e-792c-443a-a4a5-a336af39c13f.png)
